# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория видео', 'verbose_name_plural': 'Категории видео'},
        ),
        migrations.AlterModelOptions(
            name='tipa',
            options={'verbose_name': 'Категория новости', 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tipa',
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tipa',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Катекория новости'),
        ),
        migrations.AlterField(
            model_name='video',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
    ]
