# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171108_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('tip', models.CharField(max_length=55, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Musicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('ser_name', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('style', models.CharField(max_length=55, verbose_name='Стиль')),
                ('level', models.CharField(max_length=2, verbose_name='Уровень игры')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Instrument')),
            ],
            options={
                'verbose_name': 'Музыкант',
            },
        ),
    ]
