# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instrument_musicant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicant',
            options={'verbose_name': 'Музыкант', 'verbose_name_plural': 'Музыканты'},
        ),
        migrations.AlterField(
            model_name='musicant',
            name='age',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='musicant',
            name='instrument',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Instrument'),
        ),
    ]
