# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180206_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicant',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Instrument'),
        ),
    ]
