# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180206_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
    ]
