# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180206_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipInstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'типа',
                'verbose_name_plural': 'типов',
            },
        ),
    ]
